#!/usr/bin/env bash
function convert2scan {
  local colorspace
  if [ "$1" == "--gray" ]
  then
    colorspace="Gray"
    shift 
  fi

  for input in "$@"
  do
    local output="$(basename "$input" .pdf)_scan.pdf"
    
    # rotation from -0.2 to +0.2
    local rotation=$(bc -l <<< "-0.2 + 0.4 * ($RANDOM/32767)")
    
    # ensure ImageMagick is installed
    # gray scan: -colorspace Gray
    # colored scan: -colorspace sRGB
    convert \
      -density 100 \
      "$input" \
      -rotate $rotation \
      -attenuate 0.15 \
      +noise Multiplicative \
      ${colorspace:+-colorspace $colorspace} \
      -sharpen 0x1.0 \
      "$output"
  done
}

convert2scan "$@"
