#!/usr/bin/env bash
set -euo pipefail

function gauth {
  local secret_base32="${1:-}"
  if [ -z "$secret_base32" ]
  then
    echo "Usage: ${0##*/} <base32-secret>" >&2
    return 1
  fi

  while true
  do
    printf '\r%s %ss' "$(oathtool --totp --base32 "$secret_base32")" "$((30 - $(date +%s) % 30))"
    sleep 1
  done
}

gauth "$@"
