#!/usr/bin/env bash

# ipinfo.io/ip;   ipinfo.io/json
# ifconfig.co/ip; ifconfig.co/json
# ipapi.co/ip;    ipapi.co/json

function myip {
  local cmd="$1"
  [[ $# > 0 ]] && shift

  case "$cmd" in
    'internal'|'int'|'i')
      ip-internal $@
      ;;
    'external'|'ext'|'e')
      ip-external $@
      ;;
    *)
      if [ -n "$cmd" ]
      then
        echo "Unknown command '$cmd'" >&2
      fi
      echo "Usage: " >&2
      echo "   ${0##*/} int[ernal] [--interface <interface name>]" >&2
      echo "   ${0##*/} ext[ernal] [--interface <interface name>] [--details]" >&2
      
      return 1
      ;;
  esac
}

function ip-internal {
  
  local interface=$(route -n get default | grep 'interface:' | sed 's/^.*: //')
  
  while [[ $# > 0 ]]
  do
    local param_key="$1"
    shift

    case "$param_key" in
      '--interface'|'-i')
        interface="$1"
        shift
        ;;
      *)
        echo "Unknown parameter '$param_key'" >&2
        echo "Valid parameters:" >&2
        echo "    --interface <name>, -i <name>" >&2
        return 1
        ;;
    esac
  done
  
  echo $(ipconfig getifaddr "$interface")
}

function ip-external {

  local interface=$(route -n get default | grep 'interface:' | sed 's/^.*: //')
  local details=false

  while [[ $# > 0 ]]
  do
    local param_key="$1"
    shift

    case "$param_key" in
      '--interface'|'-i')
        interface="$1"
        shift
        ;;
      '--details'|'-d')
        details="true"
        ;;
      *)
        echo "Unknown parameter '$param_key'" >&2
        echo "Valid parameters:" >&2
        echo "    --interface <name>, -i <name>" >&2
        echo "    --details, -d" >&2
        return 1
        ;;
    esac
  done
  
  # TODO --ipv4
  if [ "$details" == 'true' ]
  then
    curl $interface_param "https://ipapi.co/json/" -w "\n"
  else
    curl $interface_param "https://ipapi.co/ip" -w "\n"
  fi
}

myip "$@"
