#!/usr/bin/env zsh

function pdf2scan { 
  for input in "$@"
  do
    local output="$(basename "$input" .pdf)_scan.pdf"

    # rotation from -0.5 to +0.5
    local rotation=$(( 0.2 + 0.2 * ( RANDOM % 1000 / 1000.0 ) ))
    if [ $((RANDOM % 2)) = 0 ]; then
      rotation=-$rotation
    fi

    # gray scan: -colorspace Gray
    # colored scan: -colorspace sRGB
    convert \
      -density 100 \
      $input \
      -rotate $rotation \
      -attenuate 0.2 \
      +noise Multiplicative \
      -colorspace Gray \
      -sharpen 0x1.0 \
      $output
  done
}

pdf2scan "$@"
